---
openapi: 3.0.0
info:
  title: Summer Outdoor Fun API
  description: API for various Summer Activities
  contact:
    email: bbarnett15@my.bcit.ca
  version: 1.0.0
paths:
  /stats/activity:
    get:
      tags:
        - devices
      summary: gets new summer activity stats
      operationId: app.get_activity_stats
      description: Gets summer activity stats added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of stats returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of stats returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of activity events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/bookactivity'
        "400":
          description: "invalid input, object invalid"

  /stats/weather:
    get:
      tags:
        - devices
      summary: gets new weather stats
      operationId: app.get_weather_stats
      description: Gets weather stats added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of stats returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of stats returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of weather events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/beachconditions'
        "400":
          description: "invalid input, object invalid"
  /count:
    get:
      summary: Retrieve the count of records for each event type
      description: Returns the count of records for each event type (e.g., count of event_type_1, event_type_2).
      operationId: app.get_counts
      responses:
        '200':
          description: A list of event type counts
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                example:
                  count_event_type_1: 123
                  count_event_type_2: 456
  
  /get_list_activity:
    get:
      summary: Retrieve a list of event IDs and trace IDs for activities
      description: Returns a list of event IDs and trace IDs for activities.
      operationId: app.get_list_activity
      responses:
        '200':
          description: A list of event IDs and trace IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    event_id:
                      type: string
                      description: The unique ID of the event
                    trace_id:
                      type: integer
                      description: The trace ID associated with the event
                  required:
                    - event_id
                    - trace_id
  
  /get_list_beach:
    get:
      summary: Retrieve a list of event IDs and trace IDs for beach
      description: Returns a list of event IDs and trace IDs for beach.
      operationId: app.get_list_beach
      responses:
        '200':
          description: A list of event IDs and trace IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    event_id:
                      type: string
                      description: The unique ID of the event
                    trace_id:
                      type: integer
                      description: The trace ID associated with the event
                  required:
                    - event_id
                    - trace_id

components:
  schemas:
    bookactivity:
      required:
      - booking_id
      - activity_id
      - participants
      - booking_time
      - Beach_id
      - trace_id
      type: object
      properties:
        booking_id:
          type: string
          description: The booking ID for the booked activity
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        activity_id:
          type: string
          description: Activity ID (name)
          example: Surfing Lesson
        participants:
          type: integer
          description: Number of Participants
          example: 2
        booking_time:
          type: string
          description: timestamp for when the activity takes place
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        Beach_id:
          type: string
          description: Beach ID (name)
          example: Kitsilano
        trace_id:
          type: integer
          description: Trace ID for Logging
          example: 38281221426197700

    beachconditions:
      required:
      - Device_id
      - Beach_id
      - timestamp
      - Temperature
      - Wave Height
      - trace_id
      type: object
      properties:
        Beach_id:
          type: string
          description: Beach ID (name)
          example: Kitsilano
        Device_id:
          type: string
          description: Device ID for the report
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        Temperature:
          type: integer
          description: Current Temperature of Beach (C)
          example: 30
        Wave Height:
          type: integer
          description: Current Wave Height (m)
          example: 2
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: integer
          description: Trace ID for Logging
          example: 38281221426197700

