version: 1
filename: ./data/data.json
stor_url: http://storage:8090/storage
ana_url: http://analyzer:8110/analyzer
pro_url: http://processor:8100/processor/stats
events:
  hostname: kafka
  port: 29092
  topic: events