version: 1
datastore:
  filename: ./data/data.json
scheduler:
  interval: 5
eventstores:
  beach_weather:
    url: http://storage:8090/storage/stats/weather
  beach_activity:
    url: http://storage:8090/storage/stats/activity
