version: 1
datastore:
  filename: ./data/data.json
scheduler:
  interval: 5
eventstores:
  beach_weather:
    url: http://storage/stats/weather
  beach_activity:
    url: http://storage/stats/activity
